### ISSUE TITLE
Differences from base packs?

### ISSUE THREAD

**Issue by ShiroiKuma** [fricy/DFgraphics#12]
This is a question rather than an issue. The README file says `Dwarf Fortress graphics repo for Starter Packs configured for TWBT rendering`

What changes have been made to the files? Can I just take one of these sub-modules, and stick it into my DF Install? (Assuming I've got the latest DFHack and compiled TWBT plugin) and it will just work without me needing to tweak RAW files?

**Comment by fricy** [comment]
Yes.  
Twbt doesn't need any raw tweaks, only init configures, and optional extra sprites and config files. The submodules are configured to be loaded by the PyLNP launcher, but you can manually overwrite and it should work.
