### ISSUE TITLE
Update to take advantage of PyLNP 0.10 features

### ISSUE THREAD

**Issue by PeridexisErrant** [fricy/DFgraphics#13]
Many of the raw files - all those identical to vanilla - can now be removed.

With the release of PyLNP 0.10, it's possible to specify versions of DF a graphics pack is incompatible with - along with display option like a title and tooltip, and metadata (author and version).  Supporting this would be nice - especially the version to prevent problems, and the tooltip to describe a pack.

```
{
    "author": "",
    "content_version": "",
    "df_min_version": "0.40.24",
    "title": "",
    "tooltip": ""
}
```

We can also hide TwbT-only override files from the tilesets list by prepending an underscore (the 0.10 binaries have a bug, but this is fixed in source).

If you don't mind, I might fork this and try making the above changes.  I'd also like to move everything out of submodules into a single repo, which might make remerging a pain later.  Eventually it would also be nice to write a update-to-newer-df-raws script - do you have such a thing, before I start?

**Comment by fricy** [comment]
done
